### GET 전체 Product 조회
GET http://localhost:8080/api/v1/product/all
Accept: application/json

### GET 단일 Product 조회
GET http://localhost:8080/api/v1/product/1
Accept: application/json

### POST Product 생성
POST http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "productName": "테스트 상품",
  "productPrice": 10000,
  "productStock": 50
}

### PUT Product 수정
PUT http://localhost:8080/api/v1/product/1
Content-Type: application/json

{
  "productName": "수정된 상품",
  "productPrice": 15000,
  "productStock": 30
}

### DELETE Product 삭제
DELETE http://localhost:8080/api/v1/product/5
Accept: application/json

### PATCH Product 재고 수정
PATCH http://localhost:8080/api/v1/product/1
Content-Type: application/json

{
  "productStock": 10
}