server:
  port: 8080

spring:
    config:
        import: classpath:key.yml
    datasource:
      url: jdbc:mariadb://localhost:3306/demo
      username: ${DB.USERNAME}
      password: ${DB.PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      
    jpa:
      hibernate:
        ddl-auto: update
      defer-datasource-initialization: true # 데이터 초기화
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect