spring:
    application:
        name : demo
    autoconfigure:
        exclude:
            org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

logging:
  level:
    root: INFO
